version: '3.8'

services:
    nifi:
        restart: always
        #build: .
        container_name: apache_nifi
        image: apache/nifi:1.19.0
        expose:
            - ${NIFI_INTERNAL_PORT}
        networks:
            - mydefault
        environment:
            - NIFI_WEB_HTTPS_PORT=${NIFI_INTERNAL_PORT}
            - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USER}
            - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
        ports:
            - '${NIFI_EXTERNAL_PORT}:${NIFI_INTERNAL_PORT}'
        volumes:
            - nifi_data:/var/lib/postgresql/data
            - ./drivers/mysql/mysql-connector-java-8.0.27.jar:/opt/nifi/nifi-current/lib/mysql-connector-java-8.0.27.jar
            - ./drivers/oracle/ojdbc11-21.7.0.0.jar:/opt/nifi/nifi-current/lib/ojdbc11-21.7.0.0.jar
            - ./drivers/postgresql/postgresql-42.5.1.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.1.jar
            - ./drivers/snowflake/snowflake-jdbc-3.9.2.jar:/opt/nifi/nifi-current/lib/snowflake-jdbc-3.9.2.jar
            - ./drivers/teradata/terajdbc4.jar:/opt/nifi/nifi-current/lib/terajdbc4.jar
        env_file:
            - .env
    mysqldb:
        image: mysql:8
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
        networks:
            - mydefault
            
    postgresqldb:
        image: postgres:latest
        container_name: postgresqldb
        expose:
            - ${POSTGRES_DB_PORT}
        networks:
            - mydefault
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB_NAME}
            - POSTGRES_USER=${POSTGRES_DB_USER}
            - POSTGRES_PASSWORD=${POSTGRES_DB_PW}
        ports:
            - '${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}'
        volumes:
            - db_datapg:/var/lib/postgresql/data
        env_file:
            - .env
            
networks:
    mydefault:
        driver: bridge

volumes:
    nifi_data:
    db:
    db_datapg:
